import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-white text-black dark:bg-black dark:text-white`}
      >
        <header className="border-b px-6 py-4">
          <h1 className="text-xl font-semibold">{process.env.NEXT_PUBLIC_APP_NAME ?? "Magic Proxy App"}</h1>
        </header>
        <main className="p-6 max-w-6xl mx-auto">{children}</main>
        <footer className="border-t px-6 py-4 text-sm opacity-80">
          <p>MTG proxy generator prototype. No images are generated or stored. Not affiliated with Wizards of the Coast.</p>
        </footer>
      </body>
    </html>
  );
}
